const router=require('express').Router();
const c=require('../controllers/ambulanceController');
router.get('/ambulances/rate',c.getRate);
router.get('/ambulances',c.getFleet);
router.post('/ambulances',c.createAmbulance);
router.put('/ambulances/:id',c.updateAmbulance);
router.get('/ambulance-bookings',c.getBookings);
router.get('/patients/:id/ambulance-bookings',c.getPatientBookings);
router.post('/patients/:id/ambulance-bookings',c.createBooking);
router.put('/ambulance-bookings/:id',c.updateBooking);
module.exports=router;
